# Generated by Django 3.2.9 on 2021-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Describe a peer', max_length=64, verbose_name='Description')),
                ('name', models.CharField(default='', help_text='Name of the channel', max_length=32, unique=True, verbose_name='Channel name')),
                ('username', models.CharField(default='', help_text='Username for the connection used for remote side', max_length=32, unique=True, verbose_name='Username')),
                ('secret', models.CharField(default='', help_text='Clear text password for the connection used for remote side', max_length=32, unique=True, verbose_name='Password')),
                ('registrationHere', models.BooleanField(default=False, help_text='Should remote peer register here?', verbose_name='Registration here')),
                ('registrationString', models.CharField(help_text='Registration string to remote side username:password@ip.ad.dr.es:port/extension', max_length=256, verbose_name='Registration')),
                ('callLimit', models.SmallIntegerField(default=0, help_text='Maximum calls on the trunk', verbose_name='Call Limit')),
            ],
        ),
        migrations.CreateModel(
            name='SIPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', help_text='Full name of user, description of connection', max_length=64, verbose_name='Name')),
                ('username', models.CharField(help_text='Username: 3-32 characters', max_length=32, unique=True, verbose_name='Username')),
                ('secret', models.CharField(help_text='Password for the connection', max_length=32, unique=True, verbose_name='Password')),
            ],
        ),
    ]
