# Generated by Django 3.2.9 on 2021-11-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Example: UDP + NAT for remote users', max_length=64, verbose_name='Description')),
                ('name', models.CharField(default='', help_text='Example: transport-udp-nat', max_length=32, unique=True, verbose_name='Name')),
                ('protocol', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS')], default='udp', max_length=3)),
                ('bind', models.GenericIPAddressField(default='0.0.0.0')),
                ('local_nets', models.TextField(help_text='List all local networks splitted by comma: 10.0.0.0/16, 192.168.0.0/24', max_length=256, null=True, verbose_name='local_net')),
                ('external_media_address', models.GenericIPAddressField(help_text='This is the external IP address to use in RTP handling', verbose_name='External RTP IP address')),
                ('external_signaling_address', models.GenericIPAddressField(help_text='This is much like the external_media_address setting, but for SIP signaling instead of RTP media.', verbose_name='External SIP IP address')),
            ],
        ),
        migrations.AlterField(
            model_name='sippeer',
            name='registrationString',
            field=models.CharField(blank=True, help_text='Registration string to remote side username:password@ip.ad.dr.es:port/extension', max_length=256, verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='sippeer',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pbxsetup.siptransport'),
        ),
        migrations.AddField(
            model_name='sipuser',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pbxsetup.siptransport'),
        ),
    ]
