# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0002_auto_20211130_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sippeer',
            name='description',
            field=models.CharField(default='', help_text='Describe a peer', max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='name',
            field=models.CharField(default='', help_text='Full name of user, description of connection', max_length=64, verbose_name='Name'),
        ),
    ]
