# Generated by Django 3.2.9 on 2021-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0003_auto_20211130_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siptransport',
            name='description',
            field=models.CharField(default='', help_text='Example: UDP + NAT for remote users', max_length=64, verbose_name='Description'),
        ),
    ]
