# Generated by Django 3.2.9 on 2021-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0004_alter_siptransport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siptransport',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Example: UDP + NAT for remote users', max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='siptransport',
            name='external_media_address',
            field=models.GenericIPAddressField(blank=True, help_text='This is the external IP address to use in RTP handling', null=True, verbose_name='External RTP IP address'),
        ),
        migrations.AlterField(
            model_name='siptransport',
            name='external_signaling_address',
            field=models.GenericIPAddressField(blank=True, help_text='This is much like the external_media_address setting, but for SIP signaling instead of RTP media.', null=True, verbose_name='External SIP IP address'),
        ),
        migrations.AlterField(
            model_name='siptransport',
            name='local_nets',
            field=models.CharField(blank=True, help_text='List all local networks splitted by comma: 10.0.0.0/16, 192.168.0.0/24', max_length=256, null=True, verbose_name='local_net'),
        ),
    ]
