# Generated by Django 3.2.9 on 2021-11-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0005_auto_20211130_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipuser',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sip_user_transport', to='pbxsetup.siptransport'),
        ),
    ]
