# Generated by Django 3.2.9 on 2021-11-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0006_alter_sipuser_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sippeer',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pbxsetup.siptransport'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sip_user_transport', to='pbxsetup.siptransport'),
        ),
    ]
