# Generated by Django 3.2.9 on 2021-12-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0007_auto_20211130_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sippeer',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sip_peer_transport', to='pbxsetup.siptransport'),
        ),
    ]
