# Generated by Django 3.2.9 on 2021-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0008_alter_sippeer_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='siptransport',
            name='ca_list_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siptransport',
            name='cert_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siptransport',
            name='method',
            field=models.CharField(choices=[('default', 'The default as defined by PJSIP. This is currently TLSv1'), ('tlsv1', 'TLSv1'), ('tlsv1_1', 'TLSv1.1'), ('tlsv1_2', 'TLSv1.2'), ('sslv2', 'SSLv2'), ('sslv3', 'SSLv3'), ('sslv23', 'SSLv2.3')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='siptransport',
            name='priv_key_file',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siptransport',
            name='protocol',
            field=models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS'), ('wss', 'WSS')], default='udp', max_length=3),
        ),
    ]
