# Generated by Django 3.2 on 2021-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0009_auto_20211210_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipuser',
            name='extension',
            field=models.CharField(help_text='Easy way to setup internal extension for the user', max_length=32, null=True, unique=True, verbose_name='Extension'),
        ),
    ]
