# Generated by Django 4.0.1 on 2022-01-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0010_sipuser_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sippeer',
            options={'verbose_name_plural': '3. SIP Uplinks and Peers'},
        ),
        migrations.AlterModelOptions(
            name='siptransport',
            options={'verbose_name_plural': '1. SIP Transports'},
        ),
        migrations.AlterModelOptions(
            name='sipuser',
            options={'verbose_name_plural': '2. SIP Users'},
        ),
        migrations.AddField(
            model_name='sipuser',
            name='custom_settings',
            field=models.TextField(default='', help_text='Custom user settings', null=True, verbose_name='Settings'),
        ),
    ]
