# Generated by Django 4.0.1 on 2022-03-28 21:46

from django.db import migrations, models
import pbxsetup.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0013_alter_settings_options_alter_settings_user_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siptransport',
            name='bind',
            field=models.CharField(default='0.0.0.0', max_length=256, validators=[pbxsetup.validators.validate_bind_ip]),
        ),
    ]
