# Generated by Django 4.0.1 on 2022-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0014_alter_siptransport_bind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sippeer',
            name='registrationString',
        ),
        migrations.AddField(
            model_name='sippeer',
            name='registrationThere',
            field=models.BooleanField(default=False, help_text='Should we register on remote service? Typically used for providers', verbose_name='Registration there'),
        ),
        migrations.AlterField(
            model_name='sippeer',
            name='registrationHere',
            field=models.BooleanField(default=False, help_text='Should remote peer register here? Used for GSM, E1, T1, FXS, FXO gateways, etc. ', verbose_name='Registration here'),
        ),
    ]
