# Generated by Django 4.0.1 on 2022-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0016_sippeer_host_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='user_aor_template',
            field=models.TextField(default='type = aor\nmax_contacts = 1\nremove_existing = yes', help_text='You may override it by custom settings in user form', verbose_name='User AOR template'),
        ),
        migrations.AddField(
            model_name='settings',
            name='user_auth_template',
            field=models.TextField(default='type = auth\nauth_type = userpass', help_text='You may override it by custom settings in user form', verbose_name='User auth template'),
        ),
    ]
