# Generated by Django 4.0.1 on 2022-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0017_settings_user_aor_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipuser',
            name='custom_aor_settings',
            field=models.TextField(default='', help_text='Custom user [aor] section', null=True, verbose_name='AOR Settings'),
        ),
        migrations.AddField(
            model_name='sipuser',
            name='custom_auth_settings',
            field=models.TextField(default='', help_text='Custom user [auth] section', null=True, verbose_name='Auth Settings'),
        ),
    ]
