# Generated by Django 4.0.4 on 2022-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0018_sipuser_custom_aor_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='webrtc_aor_template',
            field=models.TextField(default='type = aor\nmax_contacts = 15\nremove_existing = yes', help_text='You may override it by custom settings in user form', verbose_name='WebRTC AOR template'),
        ),
        migrations.AddField(
            model_name='settings',
            name='webrtc_auth_template',
            field=models.TextField(default='type = auth\nauth_type = userpass', help_text='You may override it by custom settings in user form', verbose_name='WebRTC auth template'),
        ),
        migrations.AddField(
            model_name='settings',
            name='webrtc_template',
            field=models.TextField(default='; WebRTC Template for Endpoint\n; -----------\n[webrtc-template-endpoint](!)\ndtls_auto_generate_cert=yes\nwebrtc=yes\ncontext=default\nmax_audio_streams = 1\nmax_video_streams = 15\ndisallow=all\nallow=opus,g722,ulaw,vp9,vp8,h264', help_text='You may override it by custom settings in user form', verbose_name='WebRTC template for endpoint'),
        ),
    ]
