# Generated by Django 4.0.4 on 2022-05-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0019_settings_webrtc_aor_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='webrtc_auth_template',
            field=models.TextField(default='type = auth\nauth_type = md5', help_text='You may override it by custom settings in user form', verbose_name='WebRTC auth template'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='webrtc_template',
            field=models.TextField(default='\ndtls_auto_generate_cert=yes\nwebrtc=yes\ncontext=default\nmax_audio_streams = 1\nmax_video_streams = 15\ndisallow=all\nallow=opus,g722,ulaw,vp9,vp8,h264', help_text='You may override it by custom settings in user form', verbose_name='WebRTC template for endpoint'),
        ),
    ]
