# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0020_alter_settings_webrtc_auth_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user_auth_template',
            field=models.TextField(default='type = auth\nauth_type = md5', help_text='You may override it by custom settings in user form', verbose_name='User auth template'),
        ),
    ]
