# Generated by Django 4.0.4 on 2022-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0021_alter_settings_user_auth_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='domain',
            field=models.CharField(default='webtel.cloud', help_text='Hostname of the server',
                                   max_length=64, unique=True, verbose_name='Hostname of the server'),
        ),
        migrations.AddField(
            model_name='settings',
            name='wss_port',
            field=models.SmallIntegerField(
                default=8089, help_text='WSS port of the server', verbose_name='WSS port of the server'),
        ),
        migrations.AddField(
            model_name='sipuser',
            name='allowed_extension',
            field=models.CharField(default='s', help_text='Only one allowed extension for the user',
                                   max_length=32, null=True, unique=False, verbose_name='Allowed extension'),
        ),
    ]
