# Generated by Django 4.0.4 on 2022-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0022_settings_domain_settings_wss_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipuser',
            name='allowed_extension',
            field=models.CharField(default='s', help_text='Only one allowed extension for the user', max_length=32, null=True, verbose_name='Allowed extension'),
        ),
    ]
