# Generated by Django 4.0.4 on 2022-06-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0023_alter_sipuser_allowed_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialplanContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use latin symbols, digits and undercore', max_length=64, unique=True, verbose_name='Context name')),
            ],
            options={
                'db_table': 'diaplan_contexts',
            },
        ),
        migrations.CreateModel(
            name='DialplanExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.CharField(default='_X!', help_text='Asterisk extension', max_length=32, verbose_name='Extension')),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Context', to='pbxsetup.dialplancontext')),
            ],
            options={
                'db_table': 'dialplan_extensions',
            },
        ),
        migrations.AddConstraint(
            model_name='dialplanextension',
            constraint=models.UniqueConstraint(fields=('context', 'ext'), name='unique extension inside context'),
        ),
    ]
