# Generated by Django 4.0.4 on 2022-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0024_dialplancontext_dialplanextension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialplanextension',
            name='dialplan',
            field=models.TextField(default='', verbose_name='Dialplan scenario'),
            preserve_default=False,
        ),
    ]
