# Generated by Django 4.0.4 on 2022-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbxsetup', '0026_dialplancontext_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialplanMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use latin symbols, digits and undercore', max_length=32, unique=True, verbose_name='Macro name')),
                ('description', models.CharField(blank=True, help_text='Use latin symbols, digits and undercore to describe', max_length=64, verbose_name='Macro description')),
                ('macro', models.TextField(verbose_name='Macro scenario')),
            ],
            options={
                'verbose_name_plural': '6. Dialplan macros',
                'db_table': 'dialplan_macros',
            },
        ),
        migrations.AlterModelOptions(
            name='dialplancontext',
            options={'verbose_name_plural': '4. Dialplan contexts'},
        ),
        migrations.AlterModelOptions(
            name='dialplanextension',
            options={'verbose_name_plural': '5. Dialplan extensions'},
        ),
    ]
